### ISSUE TITLE
how to initialize vectors for words in corpus *not* in GloVe

### ISSUE THREAD

**Issue by michaelcapizzi** [roamanalytics/mittens#7]
Not so much an issue as a question.

Do you have any suggestions on the "best" way to initialize vectors for words in my small corpus that don't appear in `GloVe`?  I'm assuming that I need to do this so that `mittens` can "retrofit" it.  But I suspect that a simple `np.random.rand(100)` is probably not the best way to go.

Any suggestions would be much appreciated.

**Comment by ndingwall** [comment]
Sorry for the slow reply - I don't get notifications for issues here for some reason.

Unless I'm misunderstanding your question, this is already dealt with in `Mittens`: you provide a `vocab` and `initial_embedding_dict` to the `.fit` method, where `vocab` can have words _not_ in `initial_embedding_dict`. So the words that don't have GloVe embeddings (i.e. appear in `vocab` but not in `initial_embedding_dict`) get initialized using the Xavier Glorot method - see https://github.com/roamanalytics/mittens/blob/master/mittens/mittens_base.py#L264. There may be better ways to initialize this but that seems to give good results.

**Comment by michaelcapizzi** [comment]
Great!  Thanks for the information.
