### ISSUE TITLE
how to use mittens for more than 20k vocab ?

### ISSUE THREAD

**Issue by akanshajainn** [roamanalytics/mittens#9]
I am trying to go through the code to understand where the changes can help in using mittens for vocab more than 20k. if you can tell me the approach or point to the part of the code that needs can be done patches to break that limitation. Or any other explanation would be helpful.

**Comment by ndingwall** [comment]
No limit is actually enforced; 20k was just an approximate guide since a (V, V) dense array is stored in memory. The only actual limit is your machine's memory.
